CREATE DATABASE NTFSScan;
GO

USE NTFSScan;
GO

CREATE TABLE Directory (
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ParentID INT NULL,
	[Name] NVARCHAR(200) NOT NULL,
	IsFile BIT NOT NULL,
	DateCreated DATETIME NULL,
	Size INT NULL
)

CREATE TABLE [Permissions] (
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	DirectoryID INT NOT NULL,
	IdentityReference NVARCHAR(200) NOT NULL,
	AccessControlType INT NOT NULL,
	FileSystemRights INT NOT NULL,
)
